# Generated by Django 4.2.30 on 2026-05-13 01:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('planner', '0002_optionpreference'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='optionpreference',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='optionpreference',
            name='scope',
            field=models.CharField(default='custom', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='optionpreference',
            unique_together={('user', 'scope', 'requirement_key')},
        ),
    ]
