# Generated by Django 4.2.30 on 2026-05-14 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='ge_path',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
