# Generated by Django 4.2.30 on 2026-05-13 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcripts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcriptentry',
            name='term',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
