# Generated by Django 4.2.30 on 2026-05-11 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TranscriptEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(choices=[('deanza', 'De Anza'), ('foothill', 'Foothill')], max_length=10)),
                ('course_code', models.CharField(max_length=20)),
                ('course_name', models.CharField(max_length=200)),
                ('units', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('grade', models.CharField(blank=True, max_length=5)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('in_progress', 'In Progress')], default='completed', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcript_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['school', 'course_code'],
                'unique_together': {('user', 'school', 'course_code')},
            },
        ),
    ]
