# Generated by Django 4.2.30 on 2026-05-11 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssistCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiving_institution_id', models.IntegerField()),
                ('sending_institution_id', models.IntegerField()),
                ('academic_year_id', models.IntegerField()),
                ('major_code', models.CharField(max_length=100)),
                ('raw_json', models.JSONField()),
                ('cached_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('receiving_institution_id', 'sending_institution_id', 'academic_year_id', 'major_code')},
            },
        ),
    ]
